version: '3.8'

x-database-variables: &db-variables
  NAME: ${NAME}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}

x-app-variables: &app-variables
  <<: *db-variables
  ALLOWED_HOSTS: 0.0.0.0
  TZ: Europe/Warsaw
  DEBUG: 1


services:
  app:
    image: exotic-website-production:latest
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
     - "8000:8000"
    environment: *app-variables
    depends_on:
      - db_migrate

  db_migrate:
    image: exotic-website-production:latest
    command: python manage.py migrate
    volumes:
      - ./app:/app
    environment: *db-variables
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment: *db-variables
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: