version: '3.8'


x-database-variables: &db-variables
  NAME: ${NAME}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  TZ: Europe/Warsaw

x-app-variables: &app-variables
  <<: *db-variables
  ALLOWED_HOSTS: 127.0.0.1, localhost
  SECRET_KEY: ${SECRET_KEY}
  TZ: Europe/Warsaw
  DEBUG: 1


services:
  app:
    image: exotic-website-production:latest
    volumes:
      - static_data:/vol/web
    environment: *app-variables
    depends_on:
      - db_migrate

  db_migrate:
    image: exotic-website-production:latest
    command: python manage.py migrate
    volumes:
      - static_data:/vol/web
    environment: *db-variables
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment: *db-variables
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  static_data:
  postgres-data: