# Generated by Django 3.1 on 2020-11-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodykit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_producer', models.CharField(blank=True, choices=[('AUD', 'Audi'), ('ACU', 'Acura'), ('BMW', 'Bmw'), ('MER', 'Mercedes-Benz'), ('BEN', 'Bentley'), ('FER', 'Ferrari'), ('MAS', 'Maserati'), ('LAM', 'Lamborghini'), ('POR', 'Porsche'), ('ROL', 'Rolls-Royce'), ('MCL', 'McLaren'), ('AST', 'Aston Martin'), ('BUG', 'Bugatti'), ('LAN', 'Land-Rover'), ('LOT', 'Lotus')], max_length=3, null=True)),
                ('image', models.ImageField(null=True, upload_to='bodykits_images', verbose_name='Bodykits')),
                ('collection', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(null=True, upload_to='logo_images', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(choices=[('AUD', 'Audi'), ('ACU', 'Acura'), ('BMW', 'Bmw'), ('MER', 'Mercedes-Benz'), ('BEN', 'Bentley'), ('FER', 'Ferrari'), ('MAS', 'Maserati'), ('LAM', 'Lamborghini'), ('POR', 'Porsche'), ('ROL', 'Rolls-Royce'), ('MCL', 'McLaren'), ('AST', 'Aston Martin'), ('BUG', 'Bugatti'), ('LAN', 'Land-Rover'), ('LOT', 'Lotus')], max_length=3, null=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Product name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('part_number', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='parts_photos', verbose_name='Photos')),
                ('use_as_main', models.BooleanField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carparts.product')),
            ],
        ),
    ]
